### ISSUE TITLE
[Android] Can not build on React-Native 0.76 old arch

### ISSUE THREAD

**Issue by PierreCapo** [Purchasely/Purchasely-ReactNative#167]
After migrating from React-Native `0.75.4` to `0.76.3`, using the old arch, I found a build compilation error on Android:
`Type mismatch: inferred type is PLYError? but Throwable was expected`
This is reported in 3-4 places within the Purchasely dependency codebase.
I am using react-native-puchasely `4.5.4`

<img width="693" alt="image" src="https://github.com/user-attachments/assets/f4ebecba-f3be-4a3f-812f-a69e717145d2">

**Comment by PierreCapo** [comment]
As a temporary workaround, casting `as Throwable` everywhere the compilation fails overcome the issue:
<img width="469" alt="image" src="https://github.com/user-attachments/assets/4ea470d0-b5a4-4290-b45f-04725e95715b">

**Comment by kherembourg** [comment]
Hello @PierreCapo 
We released yesterday our new version for React Native, **5.0.1**
This should fix your issue.

It was due to this [change](https://github.com/facebook/react-native/commit/62cbdbbcc60f9074e47416007aef81e0792d7c95) that was implemented in React Native 0.75.
We did not noticed it as we were using version 0.73, we have now upgraded to 0.76.

Thanks for your report!

**Comment by PierreCapo** [comment]
Lovely, thanks for the follow-up @kherembourg !
